name: catalogo_camisas
description: Projeto avaliativo de catalogo de camisas em Flutter para SCTEC.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Configuração dos assets para o projeto Flutter (RF05.1)
  assets:
    - assets/images/
    - assets/images/alice_in_chains.jpg
    - assets/images/bauhaus.jpg
    - assets/images/black_sabbath.jpg
    - assets/images/blind_guardian.jpg
    - assets/images/helloween.jpg
    - assets/images/rammstein.jpg
    - assets/images/sisters_of_mercy.jpg
    - assets/images/the_doors.jpg
    - assets/images/the_who.jpg
    - assets/images/type_o_negative.jpg